import ytdl from "@distube/ytdl-core";
import type { CorsOptions } from "cors";
import type { SessionOptions } from "express-session";

export const SESSION_LIFE = 10 * 60 * 1000; // 10 minutes [ 10(m) * 60(s) * 1000(ms) ]
export const tempFolderName = "tmp";

export const agent = ytdl.createAgent([
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066438,
    hostOnly: false,
    httpOnly: false,
    name: "SID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value:
      "g.a000qAgPzTD3du_Rf6ptQLvZwouRP3BidIUdHlg_4-bqqAQDd0-wlhfYEyN7FP7HJAEA3257ZAACgYKAbESARASFQHGX2Mi0saKaxRUWrMc43MteY6gJxoVAUF8yKp5fcbQjjQTyr5n7yepG_Mv0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066594,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value:
      "g.a000qAgPzTD3du_Rf6ptQLvZwouRP3BidIUdHlg_4-bqqAQDd0-wXJWCyAx0q6N_AB9j4SxjOAACgYKASMSARASFQHGX2MiVsh6q7DfSxvbefOhdiFmNhoVAUF8yKqBut0ii-ncJ2AJbmgJ00Tr0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066621,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "g.a000qAgPzTD3du_Rf6ptQLvZwouRP3BidIUdHlg_4-bqqAQDd0-wpDtzXHi0DNUWoho9Oj1_ugACgYKAbMSARASFQHGX2Mi0fED_OIsO1OR0ADBsdEegRoVAUF8yKr4op_etHw4qdVpr9OfNY1q0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066659,
    hostOnly: false,
    httpOnly: true,
    name: "HSID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value: "Au-fDckMnY18iwHBH",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066689,
    hostOnly: false,
    httpOnly: true,
    name: "SSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value: "A1uHsNBD0kTkRk7lY",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066741,
    hostOnly: false,
    httpOnly: false,
    name: "APISID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value: "8SToMz5yjTsCGmeg/AiF2X23UM-3s1u8Iv",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066773,
    hostOnly: false,
    httpOnly: false,
    name: "SAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value: "E-QR38pTMMQ9bF3Q/Au19eLWoEYPPpc8yX",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.0668,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-1PAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value: "E-QR38pTMMQ9bF3Q/Au19eLWoEYPPpc8yX",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925129.066825,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-3PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "E-QR38pTMMQ9bF3Q/Au19eLWoEYPPpc8yX",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925270.331703,
    hostOnly: false,
    httpOnly: false,
    name: "PREF",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value: "f6=40000000&tz=Africa.Cairo",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765925156.229378,
    hostOnly: false,
    httpOnly: true,
    name: "LOGIN_INFO",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "AFmmF2swRgIhAKHdYbH2OMccAf2TmcPLjb2NiHQ0c8JQakqm30cn49pdAiEAnjUs-fBxVekOwdLfxAU0PwE-oe4Jx-Pvkojt7anJIT8:QUQ3MjNmenRpc05lQ0p0ZEpTTjN2TzhlSGRsRnJ2VkQycVdtclFHV3BNU0RtdDh4RWZ1MEw5eFEzZk0zWlkzSURoS2UyeUwwSEhwTUhJOU0xSUhXQUt1X0MzVmJ2ODVpT3lDOHdyQ1BDTFVubVFZc1d4OTRwSm1mWEZKM09rWDZwWFFIWm1McVdHSVp0MUpVTVUyRkd3WXdIS1B4c0xZeGRB",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762901163.201312,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDTS",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value:
      "sidts-CjEBQT4rX_sWuZD_eXQVrQHukn4mvOVMuMgsUy7h8pV-6_d5JrKWWPZlt8PreBRnK1bNEAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762901163.201476,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDTS",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "sidts-CjEBQT4rX_sWuZD_eXQVrQHukn4mvOVMuMgsUy7h8pV-6_d5JrKWWPZlt8PreBRnK1bNEAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1731365274,
    hostOnly: false,
    httpOnly: false,
    name: "ST-tladcw",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value:
      "session_logininfo=AFmmF2swRgIhAKHdYbH2OMccAf2TmcPLjb2NiHQ0c8JQakqm30cn49pdAiEAnjUs-fBxVekOwdLfxAU0PwE-oe4Jx-Pvkojt7anJIT8%3AQUQ3MjNmenRpc05lQ0p0ZEpTTjN2TzhlSGRsRnJ2VkQycVdtclFHV3BNU0RtdDh4RWZ1MEw5eFEzZk0zWlkzSURoS2UyeUwwSEhwTUhJOU0xSUhXQUt1X0MzVmJ2ODVpT3lDOHdyQ1BDTFVubVFZc1d4OTRwSm1mWEZKM09rWDZwWFFIWm1McVdHSVp0MUpVTVUyRkd3WXdIS1B4c0xZeGRB",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1731365278,
    hostOnly: false,
    httpOnly: false,
    name: "ST-3opvp5",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value:
      "session_logininfo=AFmmF2swRgIhAKHdYbH2OMccAf2TmcPLjb2NiHQ0c8JQakqm30cn49pdAiEAnjUs-fBxVekOwdLfxAU0PwE-oe4Jx-Pvkojt7anJIT8%3AQUQ3MjNmenRpc05lQ0p0ZEpTTjN2TzhlSGRsRnJ2VkQycVdtclFHV3BNU0RtdDh4RWZ1MEw5eFEzZk0zWlkzSURoS2UyeUwwSEhwTUhJOU0xSUhXQUt1X0MzVmJ2ODVpT3lDOHdyQ1BDTFVubVFZc1d4OTRwSm1mWEZKM09rWDZwWFFIWm1McVdHSVp0MUpVTVUyRkd3WXdIS1B4c0xZeGRB",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1731365275,
    hostOnly: false,
    httpOnly: false,
    name: "ST-xuwub9",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value:
      "session_logininfo=AFmmF2swRgIhAKHdYbH2OMccAf2TmcPLjb2NiHQ0c8JQakqm30cn49pdAiEAnjUs-fBxVekOwdLfxAU0PwE-oe4Jx-Pvkojt7anJIT8%3AQUQ3MjNmenRpc05lQ0p0ZEpTTjN2TzhlSGRsRnJ2VkQycVdtclFHV3BNU0RtdDh4RWZ1MEw5eFEzZk0zWlkzSURoS2UyeUwwSEhwTUhJOU0xSUhXQUt1X0MzVmJ2ODVpT3lDOHdyQ1BDTFVubVFZc1d4OTRwSm1mWEZKM09rWDZwWFFIWm1McVdHSVp0MUpVTVUyRkd3WXdIS1B4c0xZeGRB",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762901272.966166,
    hostOnly: false,
    httpOnly: false,
    name: "SIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    value:
      "AKEyXzWVbPK-tu1ihFHu3Z1hKUAcWz58pFlZHYVf9Y7j-mVrIW0u9zFR4arZrJEq-r5wOqsR",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762901272.966311,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    value:
      "AKEyXzVay17LkOFjpIMbIAxqLSiI1MX4YruM0BvxLyvvAafY4j5itvVlfsJRqDmlzHDMj30H",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762901272.96637,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "AKEyXzX5r5PBSw5z5enercg-p6wBYerm_3a7bv5qJrBLy6SuiID4jf5WpITA7XsOyRN-X2kQ",
  },
]);

export const CORS_OPTIONS: CorsOptions = {
  origin: "https://vidl-client.vercel.app",
  credentials: true,
  methods: ["GET", "POST"],
  optionsSuccessStatus: 200,
};

export const SESSION_CONFIG: SessionOptions = {
  secret: "VIDL_SESSION",
  saveUninitialized: false,
  resave: false,
  name: "vidl_connected",
  cookie: {
    maxAge: SESSION_LIFE,
  },
};
