import type { CorsOptions } from "vite";
import ytdl from "@distube/ytdl-core";

// export const SESSION_LIFE = 3 * 60 * 60 * 1000; // 3hrs
export const tempFolderName = "tmp";

const cookies = [
  {
    name: "__Secure-1PAPISID",
    value: "eF4Cm4ltHvb1bfJ4/A6lPxkFRtAWRWKTTc",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 1,
  },
  {
    name: "__Secure-1PSID",
    value:
      "g.a000wQiFhwDHhX_s1GIyGCP9D_WGTpMCW62oOG0QAwiH8TcrHelbW6XTu92JrXevxwfNkCwDmQACgYKAVMSARYSFQHGX2MiTiZG355CrisQZNijfUWRwxoVAUF8yKqBHSzs81k1RE2E6divevuk0076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 2,
  },
  {
    name: "__Secure-1PSIDCC",
    value:
      "AKEyXzXlOvkQYJ-Ld0XbLeVcgbpFiMokQEDixUmZjHRGbWDBiZ81tdRmE35lywmwqddRh2U6",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1777327204,
    storeId: "firefox-private",
    id: 3,
  },
  {
    name: "__Secure-1PSIDTS",
    value:
      "sidts-CjIBjplskGosgDb0UwxrUJOw6SFuSMiBIBvoS08sUHamJdC-x7Ny50vgXOAf82b-uVLX1BAA",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1777327162,
    storeId: "firefox-private",
    id: 4,
  },
  {
    name: "__Secure-3PAPISID",
    value: "eF4Cm4ltHvb1bfJ4/A6lPxkFRtAWRWKTTc",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 5,
  },
  {
    name: "__Secure-3PSID",
    value:
      "g.a000wQiFhwDHhX_s1GIyGCP9D_WGTpMCW62oOG0QAwiH8TcrHelbW9UnkKn3GmdogMlhYV-vNwACgYKAcoSARYSFQHGX2Mi9f5ePJpoYKHhwOPF-mVB9RoVAUF8yKrflpHH1qh67y24JgF3X2a80076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 6,
  },
  {
    name: "__Secure-3PSIDCC",
    value:
      "AKEyXzUhSH79-L-DRCKKUBtgn_jlY6nEdxZxe29zwDMhGTN2nGZRcVpKJ2ty4Q7IBANyA7vQfA",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1777327204,
    storeId: "firefox-private",
    id: 7,
  },
  {
    name: "__Secure-3PSIDTS",
    value:
      "sidts-CjIBjplskGosgDb0UwxrUJOw6SFuSMiBIBvoS08sUHamJdC-x7Ny50vgXOAf82b-uVLX1BAA",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1777327162,
    storeId: "firefox-private",
    id: 8,
  },
  {
    name: "__Secure-ROLLOUT_TOKEN",
    value: "CPj9rMbK3JS7KRDUgPP3mfmMAxizutr6mfmMAw%3D%3D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1761342915,
    storeId: "firefox-private",
    id: 9,
  },
  {
    name: "APISID",
    value: "FIWggu_tuqU81rOP/AaLD6qobDIsbLLZG0",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 10,
  },
  {
    name: "CONSISTENCY",
    value:
      "AKreu9vIFUcxwp-2s1DrJ9mKxaki37xaxoE_lnQeRXPL5kr4CmRTvuWYzTNpmqjEyu-igeyMPVltqB48lyLIM6mJRkuc08CasD8Q8a7x5-Nu65uI5D-FHfBwpdGUXESFAQmw3YeUUe0CTlsUMSAoV9O-YQtrKwQ3Sfx_FyOJFS7Vxr4WEje5ZFBT",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791785,
    storeId: "firefox-private",
    id: 11,
  },
  {
    name: "GPS",
    value: "1",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745792709,
    storeId: "firefox-private",
    id: 12,
  },
  {
    name: "HSID",
    value: "Af0WEDX3YNQDixQjm",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 13,
  },
  {
    name: "LOGIN_INFO",
    value:
      "AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE:QUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1780351165,
    storeId: "firefox-private",
    id: 14,
  },
  {
    name: "PREF",
    value: "f4=4000000&f6=40000000&tz=Africa.Cairo",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1780351199,
    storeId: "firefox-private",
    id: 15,
  },
  {
    name: "SAPISID",
    value: "eF4Cm4ltHvb1bfJ4/A6lPxkFRtAWRWKTTc",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 16,
  },
  {
    name: "SID",
    value:
      "g.a000wQiFhwDHhX_s1GIyGCP9D_WGTpMCW62oOG0QAwiH8TcrHelb-fIX5-0o53eSt1IaZ3XG5AACgYKAf0SARYSFQHGX2MiL0YC9yAEgrZK1lspkJOMOxoVAUF8yKqHVr55K1jznHvMnLaaYhcU0076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 17,
  },
  {
    name: "SIDCC",
    value:
      "AKEyXzWktDvy8UYwpim7DGRIbM1JpZYvJ-YNC5xqyEoH0NTMPyMaUgxCrUuWZar0-LrVDekP",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1777327204,
    storeId: "firefox-private",
    id: 18,
  },
  {
    name: "SSID",
    value: "A-L58RR3dLupLoT1U",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 19,
  },
  {
    name: "ST-1b",
    value:
      "disableCache=true&itct=CBoQ8KgHGAAiEwjWvLHymvmMAxU1wUkHHVP0CA8%3D&csn=Mqr0VhOzIOZ0YRrr&session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR&endpoint=%7B%22clickTrackingParams%22%3A%22CBoQ8KgHGAAiEwjWvLHymvmMAxU1wUkHHVP0CA8%3D%22%2C%22commandMetadata%22%3A%7B%22webCommandMetadata%22%3A%7B%22url%22%3A%22%2F%22%2C%22webPageType%22%3A%22WEB_PAGE_TYPE_BROWSE%22%2C%22rootVe%22%3A3854%2C%22apiUrl%22%3A%22%2Fyoutubei%2Fv1%2Fbrowse%22%7D%7D%2C%22browseEndpoint%22%3A%7B%22browseId%22%3A%22FEwhat_to_watch%22%7D%7D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791196,
    storeId: "firefox-private",
    id: 20,
  },
  {
    name: "ST-1w0cxgk",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791179,
    storeId: "firefox-private",
    id: 21,
  },
  {
    name: "ST-3opvp5",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791204,
    storeId: "firefox-private",
    id: 22,
  },
  {
    name: "ST-8m503y",
    value:
      "itct=CAAQwrECIhMIjYvR-pr5jAMVHfJJBx034w2CmgECCDo%3D&csn=bTeRVp2SFDqBA34i&session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR&endpoint=%7B%22clickTrackingParams%22%3A%22CAAQwrECIhMIjYvR-pr5jAMVHfJJBx034w2CmgECCDo%3D%22%2C%22commandMetadata%22%3A%7B%22webCommandMetadata%22%3A%7B%22url%22%3A%22%2Fshorts%2Fq6Gy9-LuaAk%22%2C%22webPageType%22%3A%22WEB_PAGE_TYPE_SHORTS%22%2C%22rootVe%22%3A37414%7D%7D%2C%22reelWatchEndpoint%22%3A%7B%22videoId%22%3A%22q6Gy9-LuaAk%22%2C%22playerParams%22%3A%228AEByAMTuAQPogYVAe6Rh-GykhjAprrTnI_x5vxQrrHBkAcC%22%2C%22thumbnail%22%3A%7B%22thumbnails%22%3A%5B%7B%22url%22%3A%22https%3A%2F%2Fi.ytimg.com%2Fvi%2Fq6Gy9-LuaAk%2Fframe0.jpg%22%2C%22width%22%3A1080%2C%22height%22%3A1920%7D%5D%2C%22isOriginalAspectRatio%22%3Atrue%7D%2C%22overlay%22%3A%7B%22reelPlayerOverlayRenderer%22%3A%7B%22style%22%3A%22REEL_PLAYER_OVERLAY_STYLE_SHORTS%22%2C%22trackingParams%22%3A%22CD0QsLUEIhMIjYvR-pr5jAMVHfJJBx034w2C%22%2C%22reelPlayerNavigationModel%22%3A%22REEL_PLAYER_NAVIGATION_MODEL_UNSPECIFIED%22%7D%7D%2C%22params%22%3A%22CA8wAg%253D%253D%22%2C%22loggingContext%22%3A%7B%22vssLoggingContext%22%3A%7B%22serializedContextData%22%3A%22CgIIDA%253D%253D%22%7D%2C%22qoeLoggingContext%22%3A%7B%22serializedContextData%22%3A%22CgIIDA%253D%253D%22%7D%7D%2C%22ustreamerConfig%22%3A%22CAw%3D%22%2C%22identifier%22%3A%227c5432e3-0000-2337-bab0-14223bba27f6%22%2C%22sequenceParams%22%3A%22GhsKC3E2R3k5LUx1YUFrGAAgATCdw_frmp70wSgqAhgPQgBiBFJEU0g%253D%22%7D%7D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791189,
    storeId: "firefox-private",
    id: 23,
  },
  {
    name: "ST-ci3gpp",
    value:
      "disableCache=true&itct=CBMQ8agHGAAiEwjQmtvqmvmMAxVY10kHHfyQFnM%3D&csn=cRaMg8evpjy5KgiZ&endpoint=%7B%22clickTrackingParams%22%3A%22CBMQ8agHGAAiEwjQmtvqmvmMAxVY10kHHfyQFnM%3D%22%2C%22commandMetadata%22%3A%7B%22webCommandMetadata%22%3A%7B%22url%22%3A%22%2Ffeed%2Fyou%22%2C%22webPageType%22%3A%22WEB_PAGE_TYPE_BROWSE%22%2C%22rootVe%22%3A6827%2C%22apiUrl%22%3A%22%2Fyoutubei%2Fv1%2Fbrowse%22%7D%7D%2C%22browseEndpoint%22%3A%7B%22browseId%22%3A%22FElibrary%22%2C%22params%22%3A%22KgN5b3U%253D%22%7D%7D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791164,
    storeId: "firefox-private",
    id: 24,
  },
  {
    name: "ST-hcbf8d",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791190,
    storeId: "firefox-private",
    id: 25,
  },
  {
    name: "ST-jb0erv",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791188,
    storeId: "firefox-private",
    id: 26,
  },
  {
    name: "ST-l3hjtt",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791170,
    storeId: "firefox-private",
    id: 27,
  },
  {
    name: "ST-mbenfb",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791174,
    storeId: "firefox-private",
    id: 28,
  },
  {
    name: "ST-tladcw",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791203,
    storeId: "firefox-private",
    id: 29,
  },
  {
    name: "ST-xuwub9",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791205,
    storeId: "firefox-private",
    id: 30,
  },
  {
    name: "ST-yve142",
    value:
      "session_logininfo=AFmmF2swRAIgZx9pG7yvTUl5cNRJBPlmVd20Ux685_eG9NGOrYktHOYCIFxLE59pCs-egpla-xowFtKIv3emLs9vkL8Z0ZlEDPoE%3AQUQ3MjNmd3BlUS1rVmZUeVI3eGljb1FHNWZoYUFxNlk5eEFjejJZV24xak0weHpvaG1LWm8zUjluWTZFaFYzd3hZY0hUeHU4SXZYQ21MMDQ4Sk1JOWc3Tkx3R3VLYTRFS2s1Q0lYQ1I1cWk3RkUybk5YNy1obkxyTXA0U0dnQ0laVXZZQkx1bmM0a2FfYVk5anl4RDBURUo1V3NMV1BudjlR",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791196,
    storeId: "firefox-private",
    id: 31,
  },
  {
    name: "VISITOR_INFO1_LIVE",
    value: "tAJBizpMaoQ",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1761343196,
    storeId: "firefox-private",
    id: 32,
  },
  {
    name: "VISITOR_PRIVACY_METADATA",
    value: "CgJFRxIEGgAgRw%3D%3D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1761343196,
    storeId: "firefox-private",
    id: 33,
  },
  {
    name: "YSC",
    value: "EfjIkcSbyPU",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 34,
  },
  {
    name: "YTSESSION-a6l89",
    value:
      "ANPz9Khrm/ESeJhIigyXOdFxIItaS/jn8XuY/yYKxDMlcCmNxhDKMdTebq1dqmocjUfqbTmHl8tXVrwJCbSS5kW4gux9j4wt4EqyvX0=",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1745791285,
    storeId: "firefox-private",
    id: 35,
  },
];

export const agent = ytdl.createAgent(cookies);
// export const agent = ytdl.createProxyAgent(
//   { uri: "http://102.50.248.123:9172" },
//   cookies
// );

export const CORS_OPTIONS: CorsOptions = {
  origin: [/https:\/\/vidl-client\.vercel\.app/, /http:\/\/localhost:\d{4}/],
  credentials: true,
  methods: ["GET", "POST"],
  optionsSuccessStatus: 200,
};
