import ytdl from "@distube/ytdl-core";
import type { CorsOptions } from "cors";

export const SESSION_LIFE = 3 * 60 * 60 * 1000; // 3hrs
export const tempFolderName = "tmp";

const cookies = [
  {
    name: "__Secure-1PAPISID",
    value: "kjowoLUuKYH7xPbD/AMn1BDLx8pDbaKzEP",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 1,
  },
  {
    name: "__Secure-1PSID",
    value:
      "g.a000rQgPzSH-5unDLlxKGswCMlThI0rKL2rNkw0doaUmdYSnyv5jjpqx4XEi3pD7yTHxIJLAogACgYKAX0SARASFQHGX2MiogwwEZ8dAmvE4CXn0qF1JBoVAUF8yKor4HwR7vyir2kg0VDh2_UF0076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 2,
  },
  {
    name: "__Secure-1PSIDCC",
    value:
      "AKEyXzWXnsxwy7w2qt0vNAg5ZBDAG-qPdLpCyomADjl0OBgVwykofWKrpU_H0Yyfv2WYz9iJ",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1765507243,
    storeId: "firefox-private",
    id: 3,
  },
  {
    name: "__Secure-1PSIDTS",
    value:
      "sidts-CjEB7wV3sZFmtx6hObAAqUVPPmmL4YymA_fWfebyebeszkvYo3g3Se2jI5p4RWE8RVmfEAA",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1765507229,
    storeId: "firefox-private",
    id: 4,
  },
  {
    name: "__Secure-3PAPISID",
    value: "kjowoLUuKYH7xPbD/AMn1BDLx8pDbaKzEP",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 5,
  },
  {
    name: "__Secure-3PSID",
    value:
      "g.a000rQgPzSH-5unDLlxKGswCMlThI0rKL2rNkw0doaUmdYSnyv5jYOI3wDqcYmarZzLXP4jo_gACgYKAcASARASFQHGX2MiB3f0XDRo8TRHMWugo_VIoRoVAUF8yKrsrr9QD_c4FEB0_5i-cQED0076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 6,
  },
  {
    name: "__Secure-3PSIDCC",
    value:
      "AKEyXzWb8XzkK-Q7be4AfZc5rLsxYOvIcIxJC5gcOF0cp-3FaLqJrt_lDsX4O-ebytMPWl-eFg",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1765507243,
    storeId: "firefox-private",
    id: 7,
  },
  {
    name: "__Secure-3PSIDTS",
    value:
      "sidts-CjEB7wV3sZFmtx6hObAAqUVPPmmL4YymA_fWfebyebeszkvYo3g3Se2jI5p4RWE8RVmfEAA",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1765507229,
    storeId: "firefox-private",
    id: 8,
  },
  {
    name: "APISID",
    value: "MkVvRWnrV63TMaCr/AnNplhaGdruuVoqQj",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 9,
  },
  {
    name: "HSID",
    value: "Am-pRW7ifTFB-gUvs",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 10,
  },
  {
    name: "PREF",
    value: "f4=4000000&f6=40000000&tz=Africa.Cairo",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531241,
    storeId: "firefox-private",
    id: 11,
  },
  {
    name: "SAPISID",
    value: "kjowoLUuKYH7xPbD/AMn1BDLx8pDbaKzEP",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 12,
  },
  {
    name: "SID",
    value:
      "g.a000rQgPzSH-5unDLlxKGswCMlThI0rKL2rNkw0doaUmdYSnyv5jPUzQZQ-_sUzMjDmELDLdugACgYKAc0SARASFQHGX2MiDW0tH5tguQ9Hsx-Pr35PQRoVAUF8yKq6d0iP2jb90Ynnz1pJF5KI0076",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 13,
  },
  {
    name: "SIDCC",
    value:
      "AKEyXzUS7N8Nsjur95eHOf2ibbP37UXgqfPX6162T4f5R1mcshj6qwFkoYsYyAmX6ZpvzZEi",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: false,
    httpOnly: false,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1765507243,
    storeId: "firefox-private",
    id: 14,
  },
  {
    name: "SSID",
    value: "AjhQBDxtY1bTn4RFq",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1768531229,
    storeId: "firefox-private",
    id: 15,
  },
  {
    name: "VISITOR_INFO1_LIVE",
    value: "0Zauf2ak77A",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1749523238,
    storeId: "firefox-private",
    id: 16,
  },
  {
    name: "VISITOR_PRIVACY_METADATA",
    value: "CgJFRxIEGgAgGg%3D%3D",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: false,
    firstPartyDomain: "",
    partitionKey: null,
    expirationDate: 1749523238,
    storeId: "firefox-private",
    id: 17,
  },
  {
    name: "YSC",
    value: "rMV723-mdbc",
    domain: ".youtube.com",
    hostOnly: false,
    path: "/",
    secure: true,
    httpOnly: true,
    sameSite: "no_restriction",
    session: true,
    firstPartyDomain: "",
    partitionKey: null,
    storeId: "firefox-private",
    id: 18,
  },
];

export const agent = ytdl.createAgent(cookies);

export const CORS_OPTIONS: CorsOptions = {
  origin: [/https:\/\/vidl-client.vercel.app/, /http:\/\/localhost:\d{4}/],
  credentials: true,
  methods: ["GET", "POST"],
  optionsSuccessStatus: 200,
};
