import ytdl from "@distube/ytdl-core";
import type { CorsOptions } from "cors";
import type { SessionOptions } from "express-session";

export const SESSION_LIFE = 10 * 60 * 1000; // 10 minutes [ 10(m) * 60(s) * 1000(ms) ]

export const agent = ytdl.createAgent([
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661469,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-1PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "0B5AlpRHAyOb5LV8/ASxmnsIMIyvuPZaNQ",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661779,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "g.a000pgg17sBxKcYIVSTx6ndGez9q7UyRsjkcuFYB6AAneocwrrrwGUked8gZyj7iLRt1n4e_oQACgYKAUcSARMSFQHGX2MiXClRsoBmJDgLzFZ9xhM-qRoVAUF8yKof22GIStk5GdUGteuk4NJH0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762899149.271984,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "AKEyXzV9yQOBzJj4URtDaEPCZuXUAGALKe5C7ljugOunc6ARbEHxcuXZ8ddQlJEmoFSjtjSorw",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762899000.142314,
    hostOnly: false,
    httpOnly: true,
    name: "",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "sidts-CjEBQT4rX6vil4kbrO7QiC8xdi8yFthSTHLNAn_D0hvlL8oNB0gZ4fzy7DPCGlQH5fcDEAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661518,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-3PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "0B5AlpRHAyOb5LV8/ASxmnsIMIyvuPZaNQ",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661827,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "g.a000pgg17sBxKcYIVSTx6ndGez9q7UyRsjkcuFYB6AAneocwrrrwsejdNWn5PZZclcRcOvvPigACgYKAVMSARMSFQHGX2Mi7XoR4dDYQD5OFe2QVf6H_RoVAUF8yKofy8PwUE7qt3ukelS83MpZ0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762899149.272026,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "AKEyXzX3NgDPYFVREvcueryX2jVs7k2hojKsX95TXwfjdP-UrVAKEbo4pue_GtMLMzbUlHlHXjM",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762899000.142487,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDTS",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "sidts-CjEBQT4rX6vil4kbrO7QiC8xdi8yFthSTHLNAn_D0hvlL8oNB0gZ4fzy7DPCGlQH5fcDEAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661331,
    hostOnly: false,
    httpOnly: false,
    name: "APISID",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    value: "yHvMgdjfFUSdpPPn/AMoI8IShjMjbTXJ94",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661087,
    hostOnly: false,
    httpOnly: true,
    name: "HSID",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    value: "AollJ4V5WqXCQdc30",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764232053.803496,
    hostOnly: false,
    httpOnly: true,
    name: "LOGIN_INFO",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value:
      "AFmmF2swRAIgaXt0z5aFCEm4rkUxS6ygSkEuQqdD4bl1AKaaquTg_ucCICzOTfel8fa9Vs6TBohKxLzwVA2BtKuGIkSHTT-hLAEc:QUQ3MjNmejFVNFdDSGFmRERLVnVNSkhYZ3NzTURmZXF5SGM2VTBLVnBxMzhWZlA4bkR4b0U5akI1MHF5c2NFc2hlM0dUajZZNXdpVk5WNlQxdEdJTmVmRW1vbS1CM3g4LWViRmN5MnRtQTZuTXVUOHZuSWtwZUNtcHRNam9wTWRKLXVDN1BzYnFISFJ1ZHRzaWxNY2N1VHZRR0tXanVUZkpn",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1765922997.386758,
    hostOnly: false,
    httpOnly: false,
    name: "PREF",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "f6=40000000&tz=Africa.Cairo&f5=30000&f7=100&f4=4000000",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.66142,
    hostOnly: false,
    httpOnly: false,
    name: "SAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "0B5AlpRHAyOb5LV8",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.661731,
    hostOnly: false,
    httpOnly: false,
    name: "SID",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    value:
      "g.a000pgg17sBxKcYIVSTx6ndGez9q7UyRsjkcuFYB6AAneocwrrrwJKoz9ajgaMYp1geg-su00wACgYKAS4SARMSFQHGX2Mipnc1UShXCkilBnmMoG4rBxoVAUF8yKp6XPki8vLE9mumWHzfliS70076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1762899149.271878,
    hostOnly: false,
    httpOnly: false,
    name: "SIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: false,
    value:
      "AKEyXzXo1xYSxPtLzm9J2Nng4rPcBqUd_4pqQyPZJ40_yfQQ1Ic4ogr5kudZvpzIN-pThlxsLQ",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1764605254.66124,
    hostOnly: false,
    httpOnly: true,
    name: "SSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    value: "AiHRIBYGF1IiqJwrM",
  },
]);

export const CORS_OPTIONS: CorsOptions = {
  origin: true,
  credentials: true,
  methods: ["GET", "POST"],
  optionsSuccessStatus: 200,
};

export const SESSION_CONFIG: SessionOptions = {
  secret: "VIDL_SESSION",
  saveUninitialized: false,
  resave: false,
  name: "vidl_connected",
  cookie: {
    maxAge: SESSION_LIFE,
  },
};
